### ISSUE TITLE
Social media post about this board

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/osday#250]
Linkedin post:

 :mega: A new journey begin - OSDAY24

Let's start from the beginning with a new board project to keep track of all the tasks needed in order to bring our flagship event online.

Do you want to partecipate? Check out the board if there is something that interest you: https://github.com/orgs/Schrodinger-Hat/projects/15

**Comment by Readpato** [comment]
What do you think of:

📣 A new journey begins - Open Source Day 2024!

Let's start with a clean slate by creating a new project board to keep track of all the tasks needed in order to bring our flagship event online.

Would you like to collaborate in an Open Source project? Check out the board and if there is something that interests you drop us a comment: https://github.com/orgs/Schrodinger-Hat/projects/15


Edit 1: Maybe "...like to collaborate in an Open Source project..." could be "...like to collaborate and bring the project to life..."?

**Comment by Wabri** [comment]
what to add to the post:

- link 2024.osday.dev
- how to contribute to the project
- upcoming date
- where to follow the project: board+gh-project

**Comment by Readpato** [comment]
"📣 A new journey begins - [Open Source Day 2024](https://2024.osday.dev/) coming to you the [insert date]!

Let's start with a clean slate by creating a new [project board](https://github.com/orgs/Schrodinger-Hat/projects/15) to keep track of all the tasks needed in order to bring our flagship event online. This allows us to keep track of every chore that we would like to accomplish for this big event!

Would you like to collaborate with us to bring this project to life? Check the [open issues](https://github.com/Schrodinger-Hat/osday/issues) over at the GitHub repository and snatch a task that you would like to tackle on! You can also bring your own ideas to the table if you like, by proposing something over at the [project board](https://github.com/orgs/Schrodinger-Hat/projects/15)"

Last part may not be as accurate as I want it to be, but lemme know =]

**Comment by Wabri** [comment]
Done => https://www.linkedin.com/feed/update/urn:li:activity:7114557527266095104
